### ISSUE TITLE
Implement diff with existing state

### ISSUE THREAD

**Issue by itroyano** [opdev/java-helm-operator#4]
The code right now just dumps resources to the namespace.
It doesn’t check state of an existing resource like an actual controller.
It's required to add a "get and diff" action for each resource created by the chart, and apply it only if required.

**Comment by itroyano** [comment]
cc: @skattoju

**Comment by itroyano** [comment]
cc: @csviri if you have access,  this is the repo I was describing in Discord.

**Comment by csviri** [comment]
I can see it thx!
